### ISSUE TITLE
[planejamento] Janeiro de 2015

### ISSUE THREAD

**Issue by yamadapc** [haskellbr/blog#19]
A tradução da série "24 dias de Hackage" acaba no dia 1 de Janeiro. Apesar de provavelmente não manter a maratona de 1 post por dia, o HaskellBR Blog deve continuar postando textos com uma frequência (no pior dos casos) semanal.

Essa issue agrega ideias para as semanas de 1-4 do ano 2016.

- [x] **CW1** (3-9/01/2016)
- [x] **CW2** (10-16/01/2016)
- [x] **CW3** (17-23/01/2016)
- [ ] **CW4** (24-30/01/2016)

- - -

Comente com ideias e propostas que tiver. Vale notar que o [7º Haskell Meetup](https://plus.google.com/u/0/events/cojvbaipbp62v10fhh4q8ki1apc) está planejado para o dia **25/01/2016**. Portanto, assuntos em torno do meetup podem ser discutidos e gerar bons resultados durante a **CW4**.

- - -

### CW1

- [x] **(06/01)** "Sobre folds e uma pegadinha"
- [ ] ~~**(07/01)** "Os próximos 360 dias de HaskellBR"~~
- [ ] ~~**(09/01)** "Como Haskell usa meta-programação para avançar de forma independente"~~

### CW2
- [x] **(13/01)** "Meta-programação em Haskell - Parte 1 - C, LISP, Template Haskell e QuasiQuotes"
- [ ] ~~"Runnable Haskell code for your blog"~~
- [ ] ~~"Código executável em Haskell para seu blog"~~ (Não é mais possível de implementar; agora a API do glot.io requere autenticação)

### CW3
- [x] **(21/01)** "Um pouco sobre Lazy Evaluation em Haskell"

### CW4
- [x] **Post - meetup de Janeiro**

**Comment by hannelita** [comment]
#36 pode cobrir CW4? @yamadapc

**Comment by yamadapc** [comment]
Sim

**Comment by yamadapc** [comment]
Bom de mais
