### ISSUE TITLE
Post - Lazyness - parte 2

### ISSUE THREAD

**Issue by hannelita** [haskellbr/blog#37]
Explicar em detalhes NF, HNF e WHNF e como o haskell resolve expressões.

**Comment by hannelita** [comment]
@yamadapc esse aqui pode cobrir Fevereiro semana 1; abro PR até o dia 5, o que acha?

**Comment by yamadapc** [comment]
:+1: Beleza

**Comment by hannelita** [comment]
#40

**Comment by hannelita** [comment]
:+1:
